### PR TITLE
Project: Testing with RSpec (Tic-Tac-Toe)

### PR DESCRIPTION
**Pull request by Gnwin**
## RSpec Tic-Tac-Toe Test

In this project, I tested all public methods in tic _tac _toe_spec.rb. Implemented lessons learned on subject, context, expect, Test Driven Development e. t. c.

All RSpec tests passed and I also included different test case scenarios, what and what not to expect, testing positive and negative situations.

To see test results, run 'rspec' command at the root level of the project

### CODE REVIEW

**Review by Elbie-em — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED :yellow_circle:

Hello @Gnwin, I would like to congratulate you on your outstanding performance.👏🏿 Great work on creating positive and negative scenarios and making all your test cases pass. This was a great effort and I am impressed. However, there are some changes to be made so that we can have this project approved.

-  [x]  As per the concept of **encapsulation**, kindly separate the tests for each class in a separate file. Having different files for all your class tests makes your repository look professional as combining all your tests in one file can make code readability difficult as the application grows.
     - e.g the tests for the Player class can go into a file called player_spec.rb

-  [x]  Kindly add instructions on how to run tests for your application in your README file.

### Please apply the changes requested so that the project can be approved :heavy_check_mark:

### Feel free to contact me if you have any questions @Elbie-em

## HAPPY CODING 💻

**Comment by Gnwin** [comment]
Thanks for your review. I have applied all recommendations to the project.

**Review by sinansevgi — APPROVED** [review]
# Project status: Approved! :heavy_check_mark: 
----
Excellent job!. You implemented the changes requested by the previous TSE.

You can merge this pull request and continue with your journey :wave: 

----
Sinan Sevgi

**Comment by Gnwin** [comment]
Thanks, @sinansevgi. I will merge right away.

**Pull request merged**
